#!/bin/bash
# Quick script to push to GitHub

echo "========================================"
echo "Push to GitHub"
echo "========================================"
echo ""
echo "Your code is ready to push!"
echo ""
echo "Next steps:"
echo ""
echo "1. Go to https://github.com/new"
echo "2. Repository name: CCD_Data_Logger"
echo "3. Make it PUBLIC (required for free Actions)"
echo "4. Don't initialize with README"
echo "5. Click 'Create repository'"
echo ""
echo "Then run these commands (replace YOUR_USERNAME):"
echo ""
echo "git remote add origin https://github.com/YOUR_USERNAME/CCD_Data_Logger.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "========================================"
echo "After pushing:"
echo "========================================"
echo ""
echo "1. Go to your repo on GitHub"
echo "2. Click 'Actions' tab"
echo "3. Watch the APK build automatically!"
echo "4. Download APK from 'Artifacts' (after ~25 minutes)"
echo ""
